<script setup lang="ts">
import { useGenerateImageVariant } from '@core/composable/useGenerateImageVariant'
import miscMaskDark from '@images/pages/misc-mask-dark.png'
import miscMaskLight from '@images/pages/misc-mask-light.png'

const email = ref('')

const authThemeMask = useGenerateImageVariant(miscMaskLight, miscMaskDark)
</script>

<template>
  <div class="misc-wrapper" style="margin: 40px !important">
    <h1>Terms & Conditions</h1>
    <p><em>Updated at 2022-12-31</em></p>

    <h2>General Terms</h2>
    <p>
      By accessing and placing an order with RespondBuddy, you confirm that you
      are in agreement with and bound by the terms of service contained in the
      Terms & Conditions outlined below. These terms apply to the entire website
      and any email or other type of communication between you and RespondBuddy.
    </p>
    <p>
      Under no circumstances shall RespondBuddy team be liable for any direct,
      indirect, special, incidental or consequential damages, including, but not
      limited to, loss of data or profit, arising out of the use, or the
      inability to use, the materials on this site, even if RespondBuddy team or
      an authorized representative has been advised of the possibility of such
      damages. If your use of materials from this site results in the need for
      servicing, repair or correction of equipment or data, you assume any costs
      thereof.
    </p>
    <p>
      RespondBuddy will not be responsible for any outcome that may occur during
      the course of usage of our resources. We reserve the rights to change
      prices and revise the resources usage policy in any moment. This Terms &
      Conditions was created with Termify.
    </p>

    <h2>License</h2>
    <p>
      RespondBuddy grants you a revocable, non-exclusive, non-transferable,
      limited license to download, install and use the website/app strictly in
      accordance with the terms of this Agreement.
    </p>
    <p>
      These Terms & Conditions are a contract between you and RespondBuddy
      (referred to in these Terms & Conditions as "RespondBuddy", "us", "we" or
      "our"), the provider of the RespondBuddy website and the services
      accessible from the RespondBuddy website (which are collectively referred
      to in these Terms & Conditions as the "RespondBuddy Service").
    </p>
    <p>
      You are agreeing to be bound by these Terms & Conditions. If you do not
      agree to these Terms & Conditions, please do not use the RespondBuddy
      Service. In these Terms & Conditions, "you" refers both to you as an
      individual and to the entity you represent. If you violate any of these
      Terms & Conditions, we reserve the right to cancel your account or block
      access to your account without notice.
    </p>

    <h2>Definitions and Key Terms</h2>
    <p>
      To help explain things as clearly as possible in this Terms & Conditions,
      every time any of these terms are referenced, are strictly defined as:
    </p>
    <ul>
      <li>
        <strong>Cookie:</strong> small amount of data generated by a website and
        saved by your web browser. It is used to identify your browser, provide
        analytics, remember information about you such as your language
        preference or login information.
      </li>
      <li>
        <strong>Company:</strong> when this policy mentions “Company,” “we,”
        “us,” or “our,” it refers to RespondBuddy, that is responsible for your
        information under this Terms & Conditions.
      </li>
      <li>
        <strong>Country:</strong> where RespondBuddy or the owners/founders of
        RespondBuddy are based, in this case is MY
      </li>
      <li>
        <strong>Device:</strong> any internet connected device such as a phone,
        tablet, computer or any other device that can be used to visit
        RespondBuddy and use the services.
      </li>
      <li>
        <strong>Service:</strong> refers to the service provided by RespondBuddy
        as described in the relative terms (if available) and on this platform.
      </li>
      <li>
        <strong>Third-party service:</strong> refers to advertisers, contest
        sponsors, promotional and marketing partners, and others who provide our
        content or whose products or services we think may interest you.
      </li>
      <li>
        <strong>Website:</strong> RespondBuddy's site, which can be accessed via
        this URL: <a href="respondbuddy.com">respondbuddy.com</a>
      </li>
      <li>
        <strong>You:</strong> a person or entity that is registered with
        RespondBuddy to use the Services.
      </li>
    </ul>

    <h2>Restrictions</h2>
    <p>You agree not to, and you will not permit others to:</p>
    <ul>
      <li>
        License, sell, rent, lease, assign, distribute, transmit, host,
        outsource, disclose or otherwise commercially exploit the website/app or
        make the platform available to any third party.
      </li>
      <li>
        Modify, make derivative works of, disassemble, decrypt, reverse compile
        or reverse engineer any part of the website/app.
      </li>
      <li>
        Remove, alter or obscure any proprietary notice (including any notice of
        copyright or trademark) of RespondBuddy or its affiliates, partners,
        suppliers or the licensors of the website/app.
      </li>
    </ul>

    <!-- ... Other sections ... -->

    <h2>Contact Us</h2>
    <p>
      Don't hesitate to
      <a href="mailto:respondbuddy@gmail.com">contact us</a> if you have any
      questions.
    </p>

    <VImg :src="authThemeMask" class="misc-footer-img d-none d-md-block" />
  </div>
</template>

<style lang="scss">
@use '@core/scss/template/pages/misc.scss';

.misc-email-input {
  margin-inline: auto;
  max-inline-size: 21.875rem;
  min-inline-size: 12.5rem;
}
</style>

<route lang="yaml">
meta:
  layout: blank
  action: read
  subject: Auth
</route>
